[2014-11-25 05:59:19] local.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-11-25 05:59:52] local.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-11-25 06:00:03] local.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-11-25 06:00:25] local.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-11-25 06:00:53] local.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-11-25 06:01:00] local.ERROR: exception 'ErrorException' with message 'Missing argument 1 for {closure}()' in Z:\home\test1.ru\www\veer\app\routes.php:33
Stack trace:
#0 Z:\home\test1.ru\www\veer\app\routes.php(33): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', 'Z:\home\test1.r...', 33, Array)
#1 [internal function]: {closure}()
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#11 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#13 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#14 {main} [] []
[2014-11-25 06:01:27] local.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-11-25 06:01:53] local.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-11-25 07:05:22] local.ERROR: exception 'ErrorException' with message 'Missing argument 1 for {closure}()' in Z:\home\test1.ru\www\veer\app\routes.php:33
Stack trace:
#0 Z:\home\test1.ru\www\veer\app\routes.php(33): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', 'Z:\home\test1.r...', 33, Array)
#1 [internal function]: {closure}()
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#11 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#13 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#14 {main} [] []
[2014-11-25 07:05:54] local.ERROR: exception 'InvalidArgumentException' with message 'Route [indexController] not defined.' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php:209
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(430): Illuminate\Routing\UrlGenerator->route('indexController', Array, true, NULL)
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Redirector.php(173): Illuminate\Routing\UrlGenerator->action('indexController', Array)
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(211): Illuminate\Routing\Redirector->action('indexController', Array)
#3 Z:\home\test1.ru\www\veer\app\routes.php(35): Illuminate\Support\Facades\Facade::__callStatic('action', Array)
#4 Z:\home\test1.ru\www\veer\app\routes.php(35): Illuminate\Support\Facades\Redirect::action('indexController', Array)
#5 [internal function]: {closure}()
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2014-11-25 07:06:32] local.ERROR: exception 'InvalidArgumentException' with message 'Route [indexController] not defined.' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php:209
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(430): Illuminate\Routing\UrlGenerator->route('indexController', Array, true, NULL)
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Redirector.php(173): Illuminate\Routing\UrlGenerator->action('indexController', Array)
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(211): Illuminate\Routing\Redirector->action('indexController', Array)
#3 Z:\home\test1.ru\www\veer\app\routes.php(35): Illuminate\Support\Facades\Facade::__callStatic('action', Array)
#4 Z:\home\test1.ru\www\veer\app\routes.php(35): Illuminate\Support\Facades\Redirect::action('indexController', Array)
#5 [internal function]: {closure}()
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2014-11-25 07:07:32] local.ERROR: exception 'InvalidArgumentException' with message 'Route [indexController] not defined.' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php:209
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(430): Illuminate\Routing\UrlGenerator->route('indexController', Array, true, NULL)
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Redirector.php(173): Illuminate\Routing\UrlGenerator->action('indexController', Array)
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(211): Illuminate\Routing\Redirector->action('indexController', Array)
#3 Z:\home\test1.ru\www\veer\app\routes.php(35): Illuminate\Support\Facades\Facade::__callStatic('action', Array)
#4 Z:\home\test1.ru\www\veer\app\routes.php(35): Illuminate\Support\Facades\Redirect::action('indexController', Array)
#5 [internal function]: {closure}()
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2014-11-25 07:08:09] local.ERROR: exception 'InvalidArgumentException' with message 'Route [IndexController] not defined.' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php:209
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(430): Illuminate\Routing\UrlGenerator->route('IndexController', Array, true, NULL)
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Redirector.php(173): Illuminate\Routing\UrlGenerator->action('IndexController', Array)
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(211): Illuminate\Routing\Redirector->action('IndexController', Array)
#3 Z:\home\test1.ru\www\veer\app\routes.php(35): Illuminate\Support\Facades\Facade::__callStatic('action', Array)
#4 Z:\home\test1.ru\www\veer\app\routes.php(35): Illuminate\Support\Facades\Redirect::action('IndexController', Array)
#5 [internal function]: {closure}()
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2014-11-25 07:08:56] local.ERROR: exception 'InvalidArgumentException' with message 'Route [IndexController] not defined.' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php:209
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(430): Illuminate\Routing\UrlGenerator->route('IndexController', Array, true, NULL)
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Redirector.php(173): Illuminate\Routing\UrlGenerator->action('IndexController', Array)
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(208): Illuminate\Routing\Redirector->action('IndexController')
#3 Z:\home\test1.ru\www\veer\app\routes.php(43): Illuminate\Support\Facades\Facade::__callStatic('action', Array)
#4 Z:\home\test1.ru\www\veer\app\routes.php(43): Illuminate\Support\Facades\Redirect::action('IndexController')
#5 [internal function]: {closure}()
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2014-11-25 07:09:28] local.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php:932
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(932): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'Z:\home\test1.r...', 932, Array)
#1 [internal function]: Illuminate\Routing\{closure}()
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#11 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#13 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#14 {main} [] []
[2014-11-25 07:09:39] local.ERROR: exception 'BadMethodCallException' with message 'Method [] does not exist.' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:268
Stack trace:
#0 [internal function]: Illuminate\Routing\Controller->__call('', Array)
#1 [internal function]: IndexController->()
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('', Array)
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(IndexController), Object(Illuminate\Routing\Route), '')
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(934): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'IndexController', '')
#6 [internal function]: Illuminate\Routing\{closure}()
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#19 {main} [] []
[2014-11-25 07:12:13] local.ERROR: Unable to find site: No query results for model [Veer\Models\Site]. [] []
[2014-11-25 07:12:58] local.ERROR: Unable to find site: No query results for model [Veer\Models\Site]. [] []
[2014-11-25 07:13:37] local.ERROR: Unable to find site: No query results for model [Veer\Models\Site]. [] []
[2014-11-25 07:13:52] local.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' with message 'No query results for model [Veer\Models\Site].' in C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:126
Stack trace:
#0 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(44): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(22): Veer\Lib\VeerApp->isSiteAvailable('http://localhos...')
#2 C:\A\webd\server\home\test1.ru\www\veer\app\start\global.php(107): Veer\Lib\VeerApp->__construct()
#3 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\start.php(239): require('C:\A\webd\serve...')
#4 [internal function]: {closure}(Object(Illuminate\Foundation\Application))
#5 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(792): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#6 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(569): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#7 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->bootApplication()
#8 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(44): Illuminate\Foundation\Application->boot()
#9 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(33): Illuminate\Console\Application::make(Object(Illuminate\Foundation\Application))
#10 C:\A\webd\server\home\test1.ru\www\veer\artisan(26): Illuminate\Console\Application::start(Object(Illuminate\Foundation\Application))
#11 {main} [] []
[2014-11-25 07:15:00] local.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' with message 'No query results for model [Veer\Models\Site].' in C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:126
Stack trace:
#0 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(44): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(22): Veer\Lib\VeerApp->isSiteAvailable('http://localhos...')
#2 C:\A\webd\server\home\test1.ru\www\veer\app\start\global.php(107): Veer\Lib\VeerApp->__construct()
#3 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\start.php(239): require('C:\A\webd\serve...')
#4 [internal function]: {closure}(Object(Illuminate\Foundation\Application))
#5 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(792): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#6 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(569): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#7 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->bootApplication()
#8 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(44): Illuminate\Foundation\Application->boot()
#9 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(33): Illuminate\Console\Application::make(Object(Illuminate\Foundation\Application))
#10 C:\A\webd\server\home\test1.ru\www\veer\artisan(26): Illuminate\Console\Application::start(Object(Illuminate\Foundation\Application))
#11 {main} [] []
[2014-11-25 07:16:27] local.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' with message 'No query results for model [Veer\Models\Site].' in C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:126
Stack trace:
#0 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(44): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(22): Veer\Lib\VeerApp->isSiteAvailable('http://localhos...')
#2 C:\A\webd\server\home\test1.ru\www\veer\app\start\global.php(112): Veer\Lib\VeerApp->__construct()
#3 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\start.php(239): require('C:\A\webd\serve...')
#4 [internal function]: {closure}(Object(Illuminate\Foundation\Application))
#5 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(792): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#6 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(569): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#7 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->bootApplication()
#8 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(44): Illuminate\Foundation\Application->boot()
#9 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(33): Illuminate\Console\Application::make(Object(Illuminate\Foundation\Application))
#10 C:\A\webd\server\home\test1.ru\www\veer\artisan(26): Illuminate\Console\Application::start(Object(Illuminate\Foundation\Application))
#11 {main} [] []
[2014-11-25 07:17:12] local.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' with message 'No query results for model [Veer\Models\Site].' in C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:126
Stack trace:
#0 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(45): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(23): Veer\Lib\VeerApp->isSiteAvailable('http://localhos...')
#2 C:\A\webd\server\home\test1.ru\www\veer\app\start\global.php(112): Veer\Lib\VeerApp->__construct()
#3 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\start.php(239): require('C:\A\webd\serve...')
#4 [internal function]: {closure}(Object(Illuminate\Foundation\Application))
#5 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(792): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#6 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(569): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#7 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->bootApplication()
#8 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(44): Illuminate\Foundation\Application->boot()
#9 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(33): Illuminate\Console\Application::make(Object(Illuminate\Foundation\Application))
#10 C:\A\webd\server\home\test1.ru\www\veer\artisan(26): Illuminate\Console\Application::start(Object(Illuminate\Foundation\Application))
#11 {main} [] []
[2014-11-25 07:18:07] local.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' with message 'No query results for model [Veer\Models\Site].' in C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:126
Stack trace:
#0 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(45): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(23): Veer\Lib\VeerApp->isSiteAvailable('http://test1.ru...')
#2 C:\A\webd\server\home\test1.ru\www\veer\app\start\global.php(112): Veer\Lib\VeerApp->__construct()
#3 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\start.php(239): require('C:\A\webd\serve...')
#4 [internal function]: {closure}(Object(Illuminate\Foundation\Application))
#5 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(792): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#6 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(569): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#7 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->bootApplication()
#8 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(44): Illuminate\Foundation\Application->boot()
#9 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(33): Illuminate\Console\Application::make(Object(Illuminate\Foundation\Application))
#10 C:\A\webd\server\home\test1.ru\www\veer\artisan(26): Illuminate\Console\Application::start(Object(Illuminate\Foundation\Application))
#11 {main} [] []
[2014-11-25 07:18:15] local.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' with message 'No query results for model [Veer\Models\Site].' in C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:126
Stack trace:
#0 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(45): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(23): Veer\Lib\VeerApp->isSiteAvailable('http://test1.ru...')
#2 C:\A\webd\server\home\test1.ru\www\veer\app\start\global.php(112): Veer\Lib\VeerApp->__construct()
#3 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\start.php(239): require('C:\A\webd\serve...')
#4 [internal function]: {closure}(Object(Illuminate\Foundation\Application))
#5 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(792): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#6 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(569): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#7 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->bootApplication()
#8 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(44): Illuminate\Foundation\Application->boot()
#9 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(33): Illuminate\Console\Application::make(Object(Illuminate\Foundation\Application))
#10 C:\A\webd\server\home\test1.ru\www\veer\artisan(26): Illuminate\Console\Application::start(Object(Illuminate\Foundation\Application))
#11 {main} [] []
[2014-11-25 07:18:33] local.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' with message 'No query results for model [Veer\Models\Site].' in C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:126
Stack trace:
#0 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(45): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(23): Veer\Lib\VeerApp->isSiteAvailable('http://localhos...')
#2 C:\A\webd\server\home\test1.ru\www\veer\app\start\global.php(112): Veer\Lib\VeerApp->__construct()
#3 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\start.php(239): require('C:\A\webd\serve...')
#4 [internal function]: {closure}(Object(Illuminate\Foundation\Application))
#5 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(792): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#6 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(569): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#7 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->bootApplication()
#8 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(44): Illuminate\Foundation\Application->boot()
#9 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(33): Illuminate\Console\Application::make(Object(Illuminate\Foundation\Application))
#10 C:\A\webd\server\home\test1.ru\www\veer\artisan(26): Illuminate\Console\Application::start(Object(Illuminate\Foundation\Application))
#11 {main} [] []
[2014-11-25 07:18:44] local.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' with message 'No query results for model [Veer\Models\Site].' in C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:126
Stack trace:
#0 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(45): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(23): Veer\Lib\VeerApp->isSiteAvailable('http://localhos...')
#2 C:\A\webd\server\home\test1.ru\www\veer\app\start\global.php(112): Veer\Lib\VeerApp->__construct()
#3 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\start.php(239): require('C:\A\webd\serve...')
#4 [internal function]: {closure}(Object(Illuminate\Foundation\Application))
#5 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(792): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#6 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(569): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#7 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->bootApplication()
#8 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(44): Illuminate\Foundation\Application->boot()
#9 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(33): Illuminate\Console\Application::make(Object(Illuminate\Foundation\Application))
#10 C:\A\webd\server\home\test1.ru\www\veer\artisan(26): Illuminate\Console\Application::start(Object(Illuminate\Foundation\Application))
#11 {main} [] []
[2014-11-25 07:19:02] local.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' with message 'No query results for model [Veer\Models\Site].' in C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:126
Stack trace:
#0 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(45): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 C:\A\webd\server\home\test1.ru\www\veer\app\lib\veerApp.php(23): Veer\Lib\VeerApp->isSiteAvailable('http://test1.ru...')
#2 C:\A\webd\server\home\test1.ru\www\veer\app\start\global.php(112): Veer\Lib\VeerApp->__construct()
#3 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\start.php(239): require('C:\A\webd\serve...')
#4 [internal function]: {closure}(Object(Illuminate\Foundation\Application))
#5 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(792): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#6 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(569): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#7 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->bootApplication()
#8 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(44): Illuminate\Foundation\Application->boot()
#9 C:\A\webd\server\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Console\Application.php(33): Illuminate\Console\Application::make(Object(Illuminate\Foundation\Application))
#10 C:\A\webd\server\home\test1.ru\www\veer\artisan(26): Illuminate\Console\Application::start(Object(Illuminate\Foundation\Application))
#11 {main} [] []
[2014-11-25 07:38:58] local.ERROR: exception 'InvalidArgumentException' with message 'There are no commands defined in the "make" namespace.' in C:\A\webd\server\home\test1.ru\www\veer\vendor\symfony\console\Symfony\Component\Console\Application.php:514
Stack trace:
#0 C:\A\webd\server\home\test1.ru\www\veer\vendor\symfony\console\Symfony\Component\Console\Application.php(548): Symfony\Component\Console\Application->findNamespace('make')
#1 C:\A\webd\server\home\test1.ru\www\veer\vendor\symfony\console\Symfony\Component\Console\Application.php(188): Symfony\Component\Console\Application->find('make:controller')
#2 C:\A\webd\server\home\test1.ru\www\veer\vendor\symfony\console\Symfony\Component\Console\Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\A\webd\server\home\test1.ru\www\veer\artisan(28): Symfony\Component\Console\Application->run()
#4 {main} [] []
[2014-11-25 07:40:29] local.ERROR: exception 'BadMethodCallException' with message 'Method [__construct] does not exist.' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:268
Stack trace:
#0 [internal function]: Illuminate\Routing\Controller->__call('__construct', Array)
#1 [internal function]: IndexController->__construct()
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('__construct', Array)
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(IndexController), Object(Illuminate\Routing\Route), '__construct')
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(934): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'IndexController', '__construct')
#6 [internal function]: Illuminate\Routing\{closure}()
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#19 {main} [] []
[2014-11-25 07:50:41] local.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-11-25 07:54:58] local.ERROR: exception 'Illuminate\Container\BindingResolutionException' with message 'Target [IndexController] is not instantiable.' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Container\Container.php:510
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Container\Container.php(425): Illuminate\Container\Container->build('IndexController', Array)
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(463): Illuminate\Container\Container->make('IndexController', Array)
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(78): Illuminate\Foundation\Application->make('IndexController')
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(51): Illuminate\Routing\ControllerDispatcher->makeController('IndexController')
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(934): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'IndexController', 'index')
#5 [internal function]: Illuminate\Routing\{closure}()
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2014-11-25 07:55:10] local.ERROR: exception 'Illuminate\Container\BindingResolutionException' with message 'Target [IndexController] is not instantiable.' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Container\Container.php:510
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Container\Container.php(425): Illuminate\Container\Container->build('IndexController', Array)
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(463): Illuminate\Container\Container->make('IndexController', Array)
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(78): Illuminate\Foundation\Application->make('IndexController')
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(51): Illuminate\Routing\ControllerDispatcher->makeController('IndexController')
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(934): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'IndexController', 'index')
#5 [internal function]: Illuminate\Routing\{closure}()
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#16 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#17 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2014-11-25 07:59:12] local.ERROR: exception 'BadMethodCallException' with message 'Method [create] does not exist.' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:268
Stack trace:
#0 [internal function]: Illuminate\Routing\Controller->__call('create', Array)
#1 [internal function]: IndexController->create()
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('create', Array)
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(IndexController), Object(Illuminate\Routing\Route), 'create')
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(934): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'IndexController', 'create')
#6 [internal function]: Illuminate\Routing\{closure}()
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#19 {main} [] []
[2014-11-25 08:08:25] local.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, no array or string given' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php:104
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'call_user_func_...', 'Z:\home\test1.r...', 104, Array)
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(NULL, Array)
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#12 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2014-11-25 08:08:37] local.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, no array or string given' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php:104
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'call_user_func_...', 'Z:\home\test1.r...', 104, Array)
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(NULL, Array)
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#12 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2014-11-25 08:08:43] local.ERROR: exception 'ErrorException' with message 'Missing argument 2 for Illuminate\Routing\Router::any(), called in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 208 and defined' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php:215
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(215): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', 'Z:\home\test1.r...', 215, Array)
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(208): Illuminate\Routing\Router->any('/404')
#2 Z:\home\test1.ru\www\veer\app\routes.php(6): Illuminate\Support\Facades\Facade::__callStatic('any', Array)
#3 Z:\home\test1.ru\www\veer\app\routes.php(6): Illuminate\Support\Facades\Route::any('/404')
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\start.php(269): require('Z:\home\test1.r...')
#5 [internal function]: {closure}(Object(Illuminate\Foundation\Application))
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(792): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(569): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->bootApplication()
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(706): Illuminate\Foundation\Application->boot()
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#16 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#17 {main} [] []
[2014-11-25 08:08:53] local.ERROR: exception 'ErrorException' with message 'Missing argument 2 for Illuminate\Routing\Router::get(), called in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 208 and defined' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php:143
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(143): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', 'Z:\home\test1.r...', 143, Array)
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(208): Illuminate\Routing\Router->get('/404')
#2 Z:\home\test1.ru\www\veer\app\routes.php(6): Illuminate\Support\Facades\Facade::__callStatic('get', Array)
#3 Z:\home\test1.ru\www\veer\app\routes.php(6): Illuminate\Support\Facades\Route::get('/404')
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\start.php(269): require('Z:\home\test1.r...')
#5 [internal function]: {closure}(Object(Illuminate\Foundation\Application))
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(792): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(569): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->bootApplication()
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(706): Illuminate\Foundation\Application->boot()
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#16 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#17 {main} [] []
[2014-11-25 08:09:22] local.ERROR: exception 'ErrorException' with message 'Missing argument 2 for Illuminate\Routing\Router::get(), called in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 208 and defined' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php:143
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(143): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', 'Z:\home\test1.r...', 143, Array)
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(208): Illuminate\Routing\Router->get('tag/404')
#2 Z:\home\test1.ru\www\veer\app\routes.php(6): Illuminate\Support\Facades\Facade::__callStatic('get', Array)
#3 Z:\home\test1.ru\www\veer\app\routes.php(6): Illuminate\Support\Facades\Route::get('tag/404')
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\start.php(269): require('Z:\home\test1.r...')
#5 [internal function]: {closure}(Object(Illuminate\Foundation\Application))
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(792): call_user_func(Object(Closure), Object(Illuminate\Foundation\Application))
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(569): Illuminate\Foundation\Application->fireAppCallbacks(Array)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->bootApplication()
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(706): Illuminate\Foundation\Application->boot()
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#16 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#17 {main} [] []
[2014-11-25 08:10:39] local.ERROR: exception 'BadMethodCallException' with message 'Method [show404] does not exist.' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:268
Stack trace:
#0 [internal function]: Illuminate\Routing\Controller->__call('show404', Array)
#1 [internal function]: IndexController->show404()
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('show404', Array)
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(IndexController), Object(Illuminate\Routing\Route), 'show404')
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(934): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'IndexController', 'show404')
#6 [internal function]: Illuminate\Routing\{closure}()
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#19 {main} [] []
[2014-11-25 08:11:32] local.ERROR: exception 'ErrorException' with message 'Missing argument 1 for IndexController::show404()' in Z:\home\test1.ru\www\veer\app\controllers\IndexController.php:77
Stack trace:
#0 Z:\home\test1.ru\www\veer\app\controllers\IndexController.php(77): Illuminate\Exception\Handler->handleError(2, 'Missing argumen...', 'Z:\home\test1.r...', 77, Array)
#1 [internal function]: IndexController->show404()
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('show404', Array)
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(IndexController), Object(Illuminate\Routing\Route), 'show404')
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(934): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'IndexController', 'show404')
#6 [internal function]: Illuminate\Routing\{closure}()
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Route.php(104): call_user_func_array(Object(Closure), Array)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#14 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#19 {main} [] []
[2014-11-25 08:15:35] local.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:210
Stack trace:
#0 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php(196): Illuminate\Routing\RouteCollection->methodNotAllowed(Array)
#1 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php(143): Illuminate\Routing\RouteCollection->getOtherMethodsRoute(Object(Illuminate\Http\Request), Array)
#2 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#3 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#4 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#5 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Http\FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#8 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#9 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#10 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#11 Z:\home\test1.ru\www\veer\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#12 Z:\home\test1.ru\www\veer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#13 Z:\home\test1.ru\www\veer\index.php(21): Illuminate\Foundation\Application->run()
#14 {main} [] []
